// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/webhook": {
            "get": {
                "description": "do ping",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "example"
                ],
                "summary": "Handle Task Change",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ms-notification/config/scheduler_timing": {
            "post": {
                "description": "UpdateScheduledTiming",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UpdateScheduledTiming"
                ],
                "summary": "Update Scheduled Timing config",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "schedulerTiming",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UpdateSchedulerTimingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.SchedulerTiming"
                        }
                    }
                }
            }
        },
        "/ms-notification/validate": {
            "post": {
                "description": "ValidateNotification",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ValidateNotification"
                ],
                "summary": "ValidateNotification config",
                "responses": {}
            }
        },
        "/ms-notification/validate_task_due_day": {
            "post": {
                "description": "ValidateTaskDueDay",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ValidateTaskDueDay"
                ],
                "summary": "ValidateTaskDueDay config",
                "responses": {}
            }
        },
        "/ms-notification/validate_task_today": {
            "post": {
                "description": "ValidateTaskToday",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ValidateTaskToday"
                ],
                "summary": "ValidateTaskToday config",
                "responses": {}
            }
        }
    },
    "definitions": {
        "dtos.SchedulerTiming": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "org_id": {
                    "type": "string"
                },
                "purpose": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "timezone": {
                    "type": "string"
                }
            }
        },
        "dtos.UpdateSchedulerTimingRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "org_id": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "timezone": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
