name: ms-notification Bot CI

on:
  push:
      branches: [ "develop" ]

  pull_request:
      branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Package docker image
      run: docker build -t ms-notification:${{ github.sha }} .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to AWS  ECR
      id: login-ecr
      run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 452962126934.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    - name: Tag Docker image for ECR
      run: docker tag ms-notification:${{ github.sha }} 452962126934.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/ms-notification:${{ github.sha }}

    - name: Push Docker image to Amazon ECR
      run: docker push 452962126934.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/ms-notification:${{ github.sha }}
